version: '1'

services:
  web:
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    networks:
      - nginx_network
    command: bash -c ""

  checker:
    build: ./checker
    volumes:
      - ./checker/check-response.sh:/app/check-response.sh
    depends_on:
      - web
    restart: always
    networks:
      - nginx_network
networks:
  nginx_network: