services:
  web:
    image: nginx
    volumes:
      - ./templates:/etc/nginx/templates
    ports:
      - "3300"
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
    networks:
      - nginx_network
  test:
    build:
      dockerfile: ./Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - web
networks:
  nginx_network:
    external: true